name: Feature Request
description: Suggest an idea for React2Shell
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear and concise description of what you'd like to happen.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do we need this feature? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Potential Implementation
      description: Any ideas on how this could be implemented?
